/**
 * CheckResultDock — Unified Check Result Feedback
 *
 * Full dice transparency for exploration checks on the unified
 * Adventure screen (Constitution Law 6). Renders the exact
 * ResolutionSummary the Director was instructed to narrate faithfully
 * — face, modifier, DC, total, outcome. No number here is generated by
 * this component; everything comes from resolveCharacterAction() via
 * useAdventureSession's submitAction. This resurrects the dice popup
 * that lived inside the removed StoryPanel, now docked compactly over
 * the world beside the Story HUD.
 *
 * Lifecycle: the dock owns the transient display window — the same
 * 4200 ms auto-dismiss the StoryPanel popup used (and the same
 * hook-supplies-data / UI-owns-lifecycle split as CombatPanel's
 * DamageNumber) — plus a keyboard-focusable manual dismiss. Both paths
 * call the existing actions.clearCheckResult upstream. `menu-enter` is
 * in the reduced-motion kill-list, so entry is instant there.
 */

import { useEffect } from 'react'
import { PixelPanel } from '@/components/pixel'
import type { summariseCharacterAction } from '@/lib/engine'

/** Same display window the StoryPanel popup used. */
export const CHECK_RESULT_DISMISS_MS = 4200

interface CheckResultDockProps {
  result: ReturnType<typeof summariseCharacterAction>
  onDismiss: () => void
}

export function CheckResultDock({ result, onDismiss }: CheckResultDockProps) {
  const { roll, dc, stat, outcomeLabel, isSuccess } = result
  const face = roll.faces[0] ?? 0
  const isCrit = roll.isNatural20
  const isFumble = roll.isNatural1

  const variant = isCrit ? 'spirit' : isSuccess ? 'default' : 'harm'
  const resultColor = isCrit ? 'text-heal-400' : isSuccess ? 'text-arcane-300' : 'text-harm-400'

  // Auto-dismiss after the display window; re-arms if a new result
  // arrives (result identity changes), cleared on unmount.
  useEffect(() => {
    const timer = window.setTimeout(onDismiss, CHECK_RESULT_DISMISS_MS)
    return () => window.clearTimeout(timer)
  }, [result, onDismiss])

  return (
    <PixelPanel
      variant={variant}
      glow={isCrit}
      className="menu-enter p-3 max-w-xs pointer-events-auto"
      role="status"
      aria-label={`${stat} check: rolled ${face}, plus ${roll.modifier} modifier, total ${roll.total} against DC ${dc}. ${outcomeLabel}.`}
      data-testid="check-result-dock"
    >
      <div className="flex items-center justify-between gap-3 mb-1.5">
        <span className="font-pixel-display text-[8px] text-void-400 uppercase">{stat} Check</span>
        <span className="flex items-center gap-2">
          <span className="font-pixel-display text-[8px] text-void-500">DC {dc}</span>
          <button
            type="button"
            onClick={onDismiss}
            aria-label="Dismiss check result"
            className="text-void-500 hover:text-arcane-300 text-xs leading-none transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-arcane-400 rounded"
            data-testid="check-result-dismiss"
          >
            ✕
          </button>
        </span>
      </div>
      <div className="flex items-center gap-2 font-mono text-sm">
        <span className="text-white text-lg leading-none" aria-hidden="true">🎲{face}</span>
        <span className="text-void-500" aria-hidden="true">+{roll.modifier}</span>
        <span className="text-void-600" aria-hidden="true">=</span>
        <span className={`text-lg font-bold ${resultColor}`} aria-hidden="true">{roll.total}</span>
      </div>
      <p className={`font-pixel-body text-sm mt-1 ${resultColor}`}>
        {isCrit ? '✦ Critical! ' : isFumble ? '✕ Fumble. ' : ''}{outcomeLabel}
      </p>
    </PixelPanel>
  )
}
